# Generated by Django 4.1.4 on 2023-09-09 20:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0001_initial'),
        ('BoardUSer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boarduser',
            unique_together={('user', 'board')},
        ),
    ]
