# Generated by Django 4.1.4 on 2023-12-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boarduser',
            options={'verbose_name_plural': 'Board Users'},
        ),
    ]
