# Generated by Django 4.1.4 on 2024-04-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardUser', '0002_alter_boarduser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boarduser',
            options={'verbose_name': 'Pizarra - Usuario', 'verbose_name_plural': 'Pizarras - Usuarios'},
        ),
    ]
