# Generated by Django 4.1.4 on 2024-04-27 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0003_alter_board_options'),
        ('BoardUser', '0003_alter_boarduser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarduser',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardusers', to='Board.board', verbose_name='Pizarra'),
        ),
        migrations.AlterField(
            model_name='boarduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardusers', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
