# Generated by Django 4.1.4 on 2024-04-27 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0004_alter_board_options'),
        ('BoardUser', '0004_alter_boarduser_board_alter_boarduser_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boarduser',
            options={'verbose_name': 'Tablero - Usuario', 'verbose_name_plural': 'Tableros - Usuarios'},
        ),
        migrations.AlterField(
            model_name='boarduser',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardusers', to='Board.board', verbose_name='Tablero'),
        ),
    ]
