# Generated by Django 4.1.4 on 2023-05-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('title', models.CharField(max_length=45)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_consultancy', models.BooleanField()),
            ],
        ),
    ]
