# Generated by Django 4.1.4 on 2023-05-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
