# Generated by Django 4.1.4 on 2024-04-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0002_alter_board_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Pizarra', 'verbose_name_plural': 'Pizarras'},
        ),
    ]
