# Generated by Django 4.1.4 on 2024-04-27 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0003_alter_board_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Tablero', 'verbose_name_plural': 'Tableros'},
        ),
    ]
