// PATHS
export const PATH_ROOT = "/"
export const PATH_SIGNUP = "/signup/"
export const PATH_CONSULTANCY = "/consultancy/"
export const PATH_CP_CONSULT = "/controlpage/consultations/"
export const PATH_CP_CLIENTS = "/controlpage/clients/"
export const PATH_BOARD = "/board/"
export const PATH_LOGOUT = "/logout/"
export const PATH_TERMS = "/terms/"
export const PATH_CONFIRM_EMAIL = "/confirm-email/"
