version: "3.8"

services:
  backend-app:
    container_name: "backend-app"
    build:
      context: ./backend/app/
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume_prod:/usr/src/app/django_static
    command: gunicorn api_patrocinio.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 4
    expose:
      - 8000 
    env_file:
      - ./backend/.envs/.app.prod
    depends_on:
      - db
    hostname: appserver

  db:
    image: postgres:15-alpine 
    env_file: ./backend/.envs/.postgres.prod
    expose:
      - 5432
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    hostname: databaseserver

  nginx: 
        restart: always
        container_name: "nginx-frontend"
        build: ./frontend/app
        ports:
            - 80:80
        volumes:
            - static_volume_prod:/usr/src/app/django_static/
            - ./frontend/app/nginx:/etc/nginx/conf.d
        depends_on: 
            - backend-app
        hostname: nginxserver

volumes:
  postgres_data_prod:
  static_volume_prod:
