version: "3.8"

services:

  backend-app:
    restart: always
    container_name: "backend-app"
    build: ./backend/app 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/app/:/usr/src/app
      - static_volume:/usr/src/app/django_static
    ports:
      - 8000:8000
    env_file:
      - ./backend/.envs/.app.dev
    depends_on:
      - db
      - redis
    hostname: appserver


  db:
    image: postgres:15-alpine
    env_file: ./backend/.envs/.postgres.dev
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data


  frontend:
    restart: always
    container_name: "frontend"
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    expose:
        - 3000
    depends_on: 
            - backend-app
    hostname: frontend

  nginx:
        restart: always
        container_name: "proxy-nginx"
        build:
          context: ./frontend/app
          dockerfile: Dockerfile.nginx
        ports:
            - 80:80
        volumes:
            - static_volume:/usr/share/nginx/staticfiles/cms/django/
            - ./frontend/app/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - frontend
        hostname: nginxserver

  redis:
    image: "redis:alpine"
    container_name: redis_server
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume: {}
