version: "3.8"

services:

  backend-app:
    restart: always
    container_name: "backend-app"
    build: ./backend/app 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/app/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./backend/.envs/.app.dev
    depends_on:
      - db
    hostname: appserver


  db:
    image: postgres:15-alpine
    env_file: ./backend/.envs/.postgres.dev
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data


  nginx: 
        restart: always
        container_name: "nginx-frontend"
        build: ./frontend/app
        ports:
            - 80:80
        volumes:
            - static_volume:/usr/src/app/django_static/
            - ./frontend/app/nginx:/etc/nginx/conf.d
        depends_on: 
            - backend-app
        hostname: nginxserver




volumes:
  postgres_data:
  static_volume: {}
