# Generated by Django 4.1.4 on 2024-04-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['tag'], 'verbose_name': 'Tarjetas', 'verbose_name_plural': 'Tarjetas'},
        ),
    ]
