# Generated by Django 4.1.4 on 2023-07-10 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Card', '0001_initial'),
        ('Consultation', '0001_initial'),
        ('Panel', '0004_alter_panel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Consultation.consultation', verbose_name='Consultation'),
        ),
        migrations.AddField(
            model_name='card',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Panel.panel', verbose_name='Panel'),
        ),
    ]
