# Generated by Django 4.1.4 on 2023-05-02 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0003_delete_board'),
        ('Card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Panel.panel'),
        ),
    ]
