# Generated by Django 4.1.4 on 2024-04-27 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0004_alter_requestconsultation_options_and_more'),
        ('Card', '0002_alter_card_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='card', serialize=False, to='Consultation.consultation', verbose_name='Consulta'),
        ),
    ]
