# Generated by Django 4.1.4 on 2023-08-06 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0002_requestconsultation'),
        ('Card', '0003_remove_card_id_alter_card_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='card', serialize=False, to='Consultation.consultation', verbose_name='Consultation'),
        ),
    ]
