# Generated by Django 4.1.4 on 2023-08-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0004_alter_card_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='state',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned')], default='REGISTERED', max_length=12, verbose_name='Estado'),
        ),
    ]
