# Generated by Django 4.1.4 on 2023-08-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0005_card_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='state',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned')], default='CREATED', max_length=12, verbose_name='Estado'),
        ),
    ]
