# Generated by Django 4.1.4 on 2023-12-20 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Provincia')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='locality.nationality', verbose_name='Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Localidad')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='locality.province', verbose_name='Provincia')),
            ],
        ),
    ]
