# Generated by Django 4.1.4 on 2023-12-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name_plural': 'Localities'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name_plural': 'Nationalities'},
        ),
    ]
