# Generated by Django 4.1.4 on 2024-04-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0002_alter_locality_options_alter_nationality_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name': 'Nacionalidad', 'verbose_name_plural': 'Nacionalidades'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
    ]
