# Generated by Django 4.1.4 on 2024-04-27 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0004_alter_requestconsultation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Consultation.consultation', verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Comment.comment', verbose_name='Comentario'),
        ),
    ]
