# Generated by Django 4.1.4 on 2023-10-18 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='filepath',
            new_name='filename',
        ),
    ]
