# Generated by Django 4.1.4 on 2023-12-19 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Card', '0001_initial'),
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Card.card', verbose_name='Card'),
        ),
    ]
