# Generated by Django 4.1.4 on 2023-11-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0001_initial'),
        ('Calendar', '0002_alter_calendar_id_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Card.card', verbose_name='Card'),
        ),
    ]
