# Generated by Django 4.1.4 on 2024-04-27 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0003_alter_card_consultation'),
        ('Calendar', '0002_alter_calendar_options_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Card.card', verbose_name='Tarjeta'),
        ),
    ]
