# Generated by Django 4.1.4 on 2023-03-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('title', models.CharField(max_length=45)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_consultancy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('board', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
    ]
