# Generated by Django 4.1.4 on 2024-04-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panel',
            options={'verbose_name': 'Panel', 'verbose_name_plural': 'Paneles'},
        ),
    ]
