# Generated by Django 4.1.4 on 2023-07-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
