# Generated by Django 4.1.4 on 2023-07-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0002_alter_panel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
