# Generated by Django 4.1.4 on 2023-04-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0002_board_panel_delete_pelicula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
