# Generated by Django 4.1.4 on 2023-07-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0003_alter_panel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
