# Generated by Django 4.1.4 on 2023-12-19 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('id_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('PASSPORT', 'Passport')], max_length=10, verbose_name='Type of identification document')),
                ('id_value', models.CharField(max_length=20, unique=True, verbose_name='Document value')),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='FEMALE', max_length=6, verbose_name='Sex')),
                ('birth_date', models.DateField(verbose_name='Birthdate')),
                ('address', models.TextField(max_length=100, verbose_name='Address')),
                ('postal', models.IntegerField(verbose_name='Postal Code')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWER', 'Widower')], max_length=10, verbose_name='Civil status')),
                ('housing_type', models.CharField(choices=[('HOUSE', 'House'), ('DEPARTMENT', 'Department'), ('TRAILER', 'Trailer'), ('STREET_SITUATION', 'Street Situation')], max_length=20, verbose_name='Housing Type')),
                ('studies', models.CharField(choices=[('INCOMPLETE_PRIMARY', 'Incomplete Primary'), ('COMPLETE_PRIMARY', 'Complete Primary'), ('INCOMPLETE_SECONDARY', 'Incomplete Secondary'), ('COMPLETE_SECONDARY', 'Complete Secondary'), ('INCOMPLETE_TERTIARY', 'Incomplete Tertiary'), ('COMPLETE_TERTIARY', 'Complete Tertiary'), ('INCOMPLETE_UNIVERSITY', 'Incomplete University'), ('COMPLETE_UNIVERSITY', 'Complete University')], max_length=30, verbose_name='Education level')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locality.locality')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='family', serialize=False, to='Clients.client')),
                ('partner_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patrimony',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patrimony', serialize=False, to='Clients.client')),
                ('employment', models.CharField(max_length=45, verbose_name='Employment')),
                ('salary', models.IntegerField(default=0, verbose_name='Salary')),
                ('other_income', models.CharField(max_length=45, verbose_name='Otros Ingresos')),
                ('amount_other_income', models.IntegerField(default=0, verbose_name='Amount Other Income')),
                ('amount_retirement', models.IntegerField(default=0, verbose_name='Retirement Amount')),
                ('amount_pension', models.IntegerField(default=0, verbose_name='Pension Amount')),
                ('vehicle', models.CharField(max_length=300, verbose_name='Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Tel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tels', to='Clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('id_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('PASSPORT', 'Passport')], max_length=10, verbose_name='Type of identification document')),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='FEMALE', max_length=6, verbose_name='Sex')),
                ('birth_date', models.DateField(verbose_name='Birthdate')),
                ('address', models.TextField(max_length=100, verbose_name='Address')),
                ('id_value', models.CharField(max_length=20, verbose_name='Document value')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locality.locality')),
                ('family_client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Clients.family', verbose_name='family')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
