# Generated by Django 4.1.4 on 2023-05-09 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('postal', models.IntegerField(verbose_name='Código postal')),
                ('address', models.TextField(max_length=100, verbose_name='Dirección')),
                ('marital_status', models.CharField(choices=[('S', 'soltero/a'), ('C', 'Casado/a'), ('D', 'Divorciado/a'), ('V', 'Viudo')], max_length=100, verbose_name='Estado civil')),
                ('housing_type', models.CharField(choices=[('Ca', 'Casa'), ('Dp', 'Departamento'), ('CR', 'Casa Rodante'), ('SC', 'Situacion de Calle')], max_length=200, verbose_name='Tipo de Vivienda')),
                ('studies', models.CharField(choices=[('PI', 'Primario Incompleto'), ('PC', 'Primario Completo'), ('SI', 'Secundario Incompleto'), ('SC', 'Secundario Completo'), ('TI', 'Terciario Incompleto'), ('TC', 'Terciario Completo'), ('UI', 'Universitario Incompleto'), ('UC', 'Universitario Completo')], max_length=200, verbose_name='nivel de educacion alcanzado')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electronico')),
                ('id_type', models.CharField(choices=[('D', 'Documento'), ('P', 'Pasaporte')], max_length=1, verbose_name='Tipo de Documento')),
                ('id_number', models.IntegerField(unique=True, verbose_name='Número de Documento')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=1, verbose_name='Sexo')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.locality')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('partner_salary', models.IntegerField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='Clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Tel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField(verbose_name='Número de Teléfono')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tels', to='Clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('address', models.CharField(max_length=45, verbose_name='Dirección')),
                ('family_client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Clients.family')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.locality', verbose_name='Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Patrimony',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('employment', models.CharField(max_length=45, verbose_name='Empleo')),
                ('salary', models.IntegerField(default=0, verbose_name='Salario')),
                ('other_income', models.CharField(max_length=45, verbose_name='Otros Ingresos')),
                ('amount_other_income', models.IntegerField(default=0, verbose_name='Monto Otros Ingresos')),
                ('amount_retirement', models.IntegerField(default=0, verbose_name='Monto de Jubilación')),
                ('amount_pension', models.IntegerField(default=0, verbose_name='Monto de Pensión')),
                ('vehicle', models.CharField(max_length=125, verbose_name='Vehículo')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patrimony', to='Clients.client')),
            ],
        ),
    ]
