# Generated by Django 4.1.4 on 2023-09-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='housing_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('DEPARTMENT', 'Department'), ('TRAILER', 'Trailer'), ('STREET_SITUATION', 'Street Situation')], max_length=20, verbose_name='Tipo de Vivienda'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_type',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('PASSPORT', 'Passport')], max_length=10, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWER', 'Widower')], max_length=10, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='FEMALE', max_length=6, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='studies',
            field=models.CharField(choices=[('INCOMPLETE_PRIMARY', 'Primario Incompleto'), ('COMPLETE_PRIMARY', 'Primario Completo'), ('INCOMPLETE_SECONDARY', 'Secundario Incompleto'), ('COMPLETE_SECONDARY', 'Secundario Completo'), ('INCOMPLETE_TERTIARY', 'Terciario Incompleto'), ('COMPLETE_TERTIARY', 'Terciario Completo'), ('INCOMPLETE_UNIVERSITY', 'Universitario Incompleto'), ('COMPLETE_UNIVERSITY', 'Universitario Completo')], max_length=30, verbose_name='nivel de educacion alcanzado'),
        ),
    ]
