# Generated by Django 4.1.4 on 2023-05-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tel',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Número de Teléfono'),
        ),
    ]
