# Generated by Django 4.1.4 on 2023-11-14 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='family_client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Clients.family', verbose_name='family'),
        ),
        migrations.AlterField(
            model_name='son',
            name='id_value',
            field=models.CharField(default='', max_length=20, verbose_name='Document value'),
        ),
    ]
