# Generated by Django 4.1.4 on 2024-04-30 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultantes'},
        ),
    ]
