# Generated by Django 4.1.4 on 2023-11-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_alter_son_family_client_user_alter_son_id_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_value',
            field=models.CharField(max_length=20, unique=True, verbose_name='Document value'),
        ),
        migrations.AlterField(
            model_name='son',
            name='id_value',
            field=models.CharField(max_length=20, verbose_name='Document value'),
        ),
    ]
