# Generated by Django 5.0.6 on 2024-05-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Consultante', 'verbose_name_plural': 'Consultantes'},
        ),
    ]
