# Generated by Django 4.1.4 on 2023-10-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_alter_client_housing_type_alter_client_id_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='studies',
            field=models.CharField(choices=[('INCOMPLETE_PRIMARY', 'Incomplete Primary'), ('COMPLETE_PRIMARY', 'Complete Primary'), ('INCOMPLETE_SECONDARY', 'Incomplete Secondary'), ('COMPLETE_SECONDARY', 'Complete Secondary'), ('INCOMPLETE_TERTIARY', 'Incomplete Tertiary'), ('COMPLETE_TERTIARY', 'Complete Tertiary'), ('INCOMPLETE_UNIVERSITY', 'Incomplete University'), ('COMPLETE_UNIVERSITY', 'Complete University')], max_length=30, verbose_name='nivel de educacion alcanzado'),
        ),
    ]
