# Generated by Django 4.1.4 on 2024-04-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_alter_child_options_alter_family_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Hijo', 'verbose_name_plural': 'Hijos'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultantes'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Familia', 'verbose_name_plural': 'Familias'},
        ),
        migrations.AlterModelOptions(
            name='patrimony',
            options={'verbose_name': 'Patrimonio', 'verbose_name_plural': 'Patrimonios'},
        ),
        migrations.AlterModelOptions(
            name='tel',
            options={'verbose_name': 'Teléfono', 'verbose_name_plural': 'Teléfonos'},
        ),
    ]
