# Generated by Django 4.1.4 on 2023-11-03 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0001_initial'),
        ('Clients', '0003_alter_client_studies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id_number',
        ),
        migrations.AddField(
            model_name='client',
            name='id_value',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Document value'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='housing_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('DEPARTMENT', 'Department'), ('TRAILER', 'Trailer'), ('STREET_SITUATION', 'Street Situation')], max_length=20, verbose_name='Housing Type'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_type',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('PASSPORT', 'Passport')], max_length=10, verbose_name='Type of identification document'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWER', 'Widower')], max_length=10, verbose_name='Civil status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal',
            field=models.IntegerField(verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='FEMALE', max_length=6, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='client',
            name='studies',
            field=models.CharField(choices=[('INCOMPLETE_PRIMARY', 'Incomplete Primary'), ('COMPLETE_PRIMARY', 'Complete Primary'), ('INCOMPLETE_SECONDARY', 'Incomplete Secondary'), ('COMPLETE_SECONDARY', 'Complete Secondary'), ('INCOMPLETE_TERTIARY', 'Incomplete Tertiary'), ('COMPLETE_TERTIARY', 'Complete Tertiary'), ('INCOMPLETE_UNIVERSITY', 'Incomplete University'), ('COMPLETE_UNIVERSITY', 'Complete University')], max_length=30, verbose_name='Education level'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='amount_other_income',
            field=models.IntegerField(default=0, verbose_name='Amount Other Income'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='amount_pension',
            field=models.IntegerField(default=0, verbose_name='Pension Amount'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='amount_retirement',
            field=models.IntegerField(default=0, verbose_name='Retirement Amount'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='employment',
            field=models.CharField(max_length=45, verbose_name='Employment'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='vehicle',
            field=models.CharField(max_length=125, verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='son',
            name='address',
            field=models.CharField(max_length=45, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='son',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.locality', verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='tel',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
    ]
