# Generated by Django 4.1.4 on 2023-11-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_alter_client_id_value_alter_son_id_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimony',
            name='vehicle',
            field=models.CharField(max_length=300, verbose_name='Vehicle'),
        ),
    ]
