# Generated by Django 4.1.4 on 2024-04-27 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_alter_child_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='address',
            field=models.TextField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(verbose_name='Nacimiento'),
        ),
        migrations.AlterField(
            model_name='child',
            name='family_client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Clients.family', verbose_name='familia'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='child',
            name='id_type',
            field=models.CharField(choices=[('DOCUMENT', 'DNI'), ('PASSPORT', 'Pasaporte')], max_length=10, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='child',
            name='id_value',
            field=models.CharField(max_length=20, verbose_name='Num. de documento'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Femenino')], default='FEMALE', max_length=6, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(verbose_name='Nacimiento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='housing_type',
            field=models.CharField(choices=[('HOUSE', 'Casa'), ('DEPARTMENT', 'Departamento'), ('TRAILER', 'Remolque'), ('STREET_SITUATION', 'Situación de calle')], max_length=20, verbose_name='Vivienda'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_type',
            field=models.CharField(choices=[('DOCUMENT', 'DNI'), ('PASSPORT', 'Pasaporte')], max_length=10, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_value',
            field=models.CharField(max_length=20, unique=True, verbose_name='Num. de documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'Soltero/a'), ('MARRIED', 'Casado/a'), ('DIVORCED', 'Divorciado/a'), ('WIDOWER', 'Viudo/a')], max_length=10, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal',
            field=models.IntegerField(verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Femenino')], default='FEMALE', max_length=6, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='studies',
            field=models.CharField(choices=[('INCOMPLETE_PRIMARY', 'Primario incompleto'), ('COMPLETE_PRIMARY', 'Primario completo'), ('INCOMPLETE_SECONDARY', 'Secundario incompleto'), ('COMPLETE_SECONDARY', 'Secundario completo'), ('INCOMPLETE_TERTIARY', 'Terciario incompleto'), ('COMPLETE_TERTIARY', 'Terciario complero'), ('INCOMPLETE_UNIVERSITY', 'Iniversidad incompleta'), ('COMPLETE_UNIVERSITY', 'Universidad completa')], max_length=30, verbose_name='Estudios'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='amount_other_income',
            field=models.IntegerField(default=0, verbose_name='Ingreso por otros ingresos'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='amount_pension',
            field=models.IntegerField(default=0, verbose_name='Ingreso por pensión'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='amount_retirement',
            field=models.IntegerField(default=0, verbose_name='Ingreso por jubilación'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='employment',
            field=models.CharField(max_length=45, verbose_name='Empleo'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='vehicle',
            field=models.CharField(max_length=300, verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='tel',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Número de teléfono'),
        ),
    ]
