# Generated by Django 4.1.4 on 2023-11-08 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_remove_client_id_number_client_id_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimony',
            name='id',
        ),
        migrations.AlterField(
            model_name='family',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='Clients.client'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patrimony', serialize=False, to='Clients.client'),
        ),
    ]
