# Generated by Django 4.1.4 on 2023-11-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_remove_patrimony_id_alter_family_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patrimony',
            old_name='client',
            new_name='id',
        ),
    ]
