# Generated by Django 4.1.4 on 2023-07-10 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=12, verbose_name='Estado')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('opponent', models.CharField(max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultations', to='Clients.client', verbose_name='Client')),
            ],
        ),
    ]
