# Generated by Django 4.1.4 on 2024-04-30 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Board", "0001_initial"),
        ("Clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "availability_state",
                    models.CharField(
                        choices=[
                            ("CREATED", "Creado, sin asignar"),
                            ("PENDING", "Solicitud de asignación pendiente"),
                            ("ASSIGNED", "Asignado"),
                            ("REJECTED", "Rechazado, sin asignar"),
                            ("ARCHIVED", "Archivado"),
                        ],
                        default="CREATED",
                        max_length=12,
                        verbose_name="Estado de disponibilidad",
                    ),
                ),
                (
                    "progress_state",
                    models.CharField(
                        choices=[
                            ("TODO", "Por hacer"),
                            ("IN_PROGRESS", "En progreso"),
                            ("DONE", "Terminado"),
                            ("PAUSED", "Pausado"),
                            ("BLOCKED", "Bloqueado"),
                            ("INCOMPLETE", "Incompleto"),
                        ],
                        default="TODO",
                        max_length=12,
                        verbose_name="Estado de progreso",
                    ),
                ),
                ("time_stamp", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("opponent", models.CharField(max_length=500)),
                ("tag", models.CharField(max_length=30)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="consultations",
                        to="Clients.client",
                        verbose_name="Consultante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
            },
        ),
        migrations.CreateModel(
            name="RequestConsultation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("ACCEPTED", "Aceptado"),
                            ("REJECTED", "Rechazado"),
                        ],
                        default="PENDING",
                        max_length=12,
                        verbose_name="Estado de solicitud",
                    ),
                ),
                (
                    "resolution_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tiempo de resolución"
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_consultations",
                        to="Consultation.consultation",
                        verbose_name="Consulta",
                    ),
                ),
                (
                    "destiny_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_consultations",
                        to="Board.board",
                        verbose_name="Tablero de destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de consulta",
                "verbose_name_plural": "Solicitudes de consultas",
                "unique_together": {("consultation", "state", "resolution_timestamp")},
            },
        ),
    ]
