# Generated by Django 4.1.4 on 2023-11-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
