# Generated by Django 4.1.4 on 2023-08-24 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestconsultation',
            name='id',
        ),
        migrations.AlterField(
            model_name='requestconsultation',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='request_consultations', serialize=False, to='Consultation.consultation', verbose_name='Consulta'),
        ),
    ]
