# Generated by Django 4.1.4 on 2024-04-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0002_alter_requestconsultation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='requestconsultation',
            options={'verbose_name': 'Solicitud de Consulta', 'verbose_name_plural': 'Solicitudes de Consultas'},
        ),
    ]
