# Generated by Django 4.1.4 on 2023-08-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0003_alter_consultation_client_alter_consultation_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=12, verbose_name='Estado'),
        ),
    ]
