# Generated by Django 4.1.4 on 2023-09-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0003_alter_requestconsultation_destiny_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='state',
        ),
        migrations.AddField(
            model_name='consultation',
            name='availability_state',
            field=models.CharField(choices=[('CREATED', 'Unassigned Created'), ('PENDING', 'Pending Assignment Request'), ('ASSIGNED', 'Assigned'), ('REJECTED', 'Unassigned Rejected')], default='CREATED', max_length=12, verbose_name='Availability State'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='progress_state',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('PAUSED', 'Paused'), ('BLOCKED', 'Blocked')], default='TODO', max_length=12, verbose_name='Progress State'),
        ),
    ]
