# Generated by Django 4.1.4 on 2023-09-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0004_remove_consultation_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='availability_state',
            field=models.CharField(choices=[('CREATED', 'Unassigned Created'), ('PENDING', 'Pending Assignment Request'), ('ASSIGNED', 'Assigned'), ('REJECTED', 'Unassigned Rejected'), ('ARCHIVED', 'Archived')], default='CREATED', max_length=12, verbose_name='Availability State'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='progress_state',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('PAUSED', 'Paused'), ('BLOCKED', 'Blocked'), ('INCOMPLETE', 'Incomplete')], default='TODO', max_length=12, verbose_name='Progress State'),
        ),
    ]
