# Generated by Django 4.1.4 on 2023-10-17 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_alter_client_studies'),
        ('Consultation', '0005_alter_consultation_availability_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultations', to='Clients.client', verbose_name='Client'),
        ),
    ]
