name: Continuous Integration

# triggers for our workflow
on:
  # any code pushed to master and develop branch will also be a trigger
  push:
    branches:
      - main
      - dev


jobs:
  ci: # health check job for testing and code formatting check
    name: Run test
    runs-on: ubuntu-22.04 # os for running the job
    container:
      python:3.11.1-alpine 

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }} 
    
      - name: Set api environment
        run: |
          set > "com/backend/.envs/.app.dev"
      
      - name: virtual environment
        run: |
          cd com/backend/app/
          python -m  venv env
      
      - name: Install Dependencies
        run: |
          ls
          cd com/backend/app/
          source  env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: run test
        run: |
          cd ./com/backend/app
          source  ./env/bin/activate
          python ./manage.py test          
        env: 
          DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 0.0.0.0 databaseserver db nginxserver"
          DEBUG: 1
          SECRET_KEY: qlz[43I@dG3[UwyYV*P0Gg:1me"F0mMauxn"ZTKPS4"$"?+s!2Fn
          EMAIL_HOST_USER: patrociniouba1@gmail.com
          EMAIL_HOST_PASSWORD: woohhaievkrqclqv
          CORS_ALLOWED_ORIGINS: "http://127.0.0.1:3000 http://localhost:3000 http://127.0.0.1:80 http://localhost http://nginxserver"
          HOSTNAME: localhost
          
  

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }} 
      - name: Build and Push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: proyectopatrocinio/patrocinio
          registry: docker.io
          dockerfile: com/backend/app/Dockerfile
          directory: com/backend/app          
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
