name: Continuous Integration

# triggers for our workflow
on:
  # any code pushed to master and develop branch will also be a trigger
  push:
    branches:
      - main
      - dev


jobs:
  ci: # health check job for testing and code formatting check
    name: Run test
    runs-on: ubuntu-22.04 # os for running the job
    container:
      node:16-alpine 

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
    
      - name: Set environments
        run: |
          set > "com/frontend/app/.env"

      
      - name: Install Dependencies
        run: |
          cd com/frontend/app/
          npm install
          npm run build --no-cache

      - name: run test
        run: |
          cd ./com/frontend/app
          npm test
        env: 
          DEBUG: 1


  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }} 
      - name: Build and Push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: proyectopatrocinio/frontend-patrocinio
          registry: docker.io
          dockerfile: com/frontend/app/Dockerfile.prod
          directory: com/frontend/app
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
